# Resolve react_native_pods.rb with node to allow for hoisting
require '/Users/yinsw1994/myproject/drone_rental_platform/drone_Rental_platform_v1/mobile/node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '15.1'

# 强制禁用 New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# 手动定义 config，并使用 use_native_modules
config = use_native_modules!
# 如果 use_native_modules! 返回 nil，则使用默认配置
if config.nil?
  config = { reactNativePath: '../node_modules/react-native' }
end

target 'WurenjiMobile' do
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
