const isProductionBuild = process.env.NODE_ENV === 'production';
const devOnlySubPackages = isProductionBuild ? [] : [
  { root: 'pages/dev', pages: ['subscribe-test/index'] },
];

export default defineAppConfig({
  pages: [
    'pages/auth/mode-selection/index',
    'pages/auth/login/index','pages/auth/register/index',
    'pages/home/index',
    'pages/messages/index',
    'pages/profile/index',
    'pages/profile/my-demands/index','pages/profile/my-offers/index','pages/profile/my-quotes/index',
    'pages/profile/owner/index','pages/profile/pilot/index','pages/profile/drones/index',
    'pages/provider-demand/index',
    'pages/orders/index',
    'pages/orders/provider/index',
    'pages/orders/detail/index',
    'pages/orders/anomaly-list/index',
    'pages/orders/contract/index',
    'pages/orders/live/index',
  ],
  lazyCodeLoading: 'requiredComponents',
  subPackages: [
    { root: 'pages/provider', pages: ['onboarding/index'] },
    { root: 'pages/chat', pages: ['index'] },
    { root: 'pages/customer-service', pages: ['index'] },
    { root: 'pages/demand', pages: ['detail/index', 'quote/index'] },
    { root: 'pages/supply', pages: ['detail/index', 'list/index'] },
    { root: 'pages/market', pages: ['index'] },
    { root: 'pages/dispatch', pages: ['waiting/index', 'list/index', 'detail/index', 'create/index'] },
    { root: 'pages/payment', pages: ['index'] },
    { root: 'pages/after-sale', pages: ['index'] },
    { root: 'pages/review', pages: ['index'] },
    { root: 'pages/publish', pages: ['demand/index', 'supply/index', 'cargo/index', 'quick-order/index'] },
    { root: 'pages/flight', pages: ['monitor/index', 'records/index', 'trajectory/index', 'multi-point/index'] },
    { root: 'pages/pilot', pages: ['workbench/index', 'register/index', 'bind-drone/index'] },
    { root: 'pages/settings', pages: ['index'] },
    { root: 'pages/edit-profile', pages: ['index'] },
    { root: 'pages/verification', pages: ['index'] },
    { root: 'pages/certification', pages: ['index'] },
    { root: 'pages/credit', pages: ['score/index', 'deposit/index', 'violation/index'] },
    { root: 'pages/insurance', pages: ['policy/index', 'claim/index'] },
    { root: 'pages/fulfillment', pages: ['hub/index', 'safety-check/index'] },
    { root: 'pages/cargo', pages: ['list/index', 'detail/index', 'accept/index'] },
    { root: 'pages/airspace', pages: ['index', 'no-fly/index'] },
    { root: 'pages/compliance', pages: ['index'] },
    { root: 'pages/client', pages: ['profile/index', 'register/index'] },
    { root: 'pages/owner', pages: ['bind-pilot/index'] },
    { root: 'pages/address', pages: ['index', 'book/index'] },
    { root: 'pages/drone', pages: ['add/index', 'edit/index', 'detail/index', 'certification/index', 'maintenance/index', 'nearby/index'] },
    { root: 'pages/settlement', pages: ['wallet/index', 'withdrawal/index', 'withdrawal-list/index'] },
    ...devOnlySubPackages,
  ],
  window: { backgroundTextStyle: 'light', navigationBarBackgroundColor: '#fff', navigationBarTitleText: '重载吊运', navigationBarTextStyle: 'black' },
  permission: {
    'scope.userLocation': {
      desc: '上线接单时需要获取你的位置，向附近的客户展示',
    },
  },
  requiredPrivateInfos: ['getLocation', 'chooseLocation'],
  tabBar: {
    custom: true,
    color: '#999999', selectedColor: '#1677ff', backgroundColor: '#ffffff', borderStyle: 'black',
    list: [
      { pagePath: 'pages/home/index', text: '首页' },
      { pagePath: 'pages/orders/index', text: '订单' },
      { pagePath: 'pages/provider-demand/index', text: '接单需求' },
      { pagePath: 'pages/messages/index', text: '消息' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
});
