export default defineAppConfig({
  pages: [
    'pages/auth/login/index','pages/auth/register/index',
    'pages/home/index',
    'pages/messages/index','pages/chat/index',
    'pages/profile/index',
    'pages/profile/my-demands/index','pages/profile/my-offers/index','pages/profile/my-quotes/index',
    'pages/profile/owner/index','pages/profile/pilot/index','pages/profile/drones/index',
    'pages/demand/detail/index','pages/supply/detail/index',
    'pages/demand/list/index',
    'pages/demand/quote/index',
    'pages/market/index',
    'pages/supply/list/index',
    'pages/orders/index',
    'pages/orders/detail/index',
    'pages/orders/anomaly-list/index',
    'pages/orders/contract/index',
    'pages/dispatch/list/index','pages/dispatch/detail/index','pages/dispatch/create/index',
    'pages/payment/index','pages/after-sale/index','pages/review/index',
    'pages/publish/demand/index','pages/publish/supply/index','pages/publish/cargo/index',
    'pages/publish/quick-order/index',
    'pages/flight/monitor/index','pages/flight/records/index',
    'pages/pilot/workbench/index',
    'pages/pilot/register/index',
    'pages/settings/index','pages/edit-profile/index','pages/verification/index','pages/certification/index',
    'pages/credit/score/index','pages/credit/deposit/index','pages/credit/violation/index',
    'pages/insurance/policy/index','pages/insurance/claim/index',
    'pages/fulfillment/hub/index',
    'pages/cargo/list/index','pages/cargo/detail/index','pages/cargo/accept/index',
    'pages/airspace/index','pages/airspace/no-fly/index','pages/compliance/index',
    'pages/client/profile/index','pages/client/register/index',
    'pages/owner/bind-pilot/index','pages/pilot/bind-drone/index',
    'pages/address/index',
    'pages/flight/trajectory/index',
    'pages/flight/multi-point/index',
    'pages/drone/add/index',
    'pages/drone/edit/index',
    'pages/drone/detail/index',
    'pages/drone/certification/index',
    'pages/drone/maintenance/index',
    'pages/drone/nearby/index',
    'pages/settlement/wallet/index',
    'pages/settlement/withdrawal/index',
    'pages/settlement/withdrawal-list/index',
  ],
  window: { backgroundTextStyle: 'light', navigationBarBackgroundColor: '#fff', navigationBarTitleText: '无人机吊运', navigationBarTextStyle: 'black' },
  tabBar: {
    custom: true,
    color: '#999999', selectedColor: '#1677ff', backgroundColor: '#ffffff', borderStyle: 'black',
    list: [
      { pagePath: 'pages/home/index', text: '工作台' },
      { pagePath: 'pages/messages/index', text: '消息' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
});
